// ----------------------------------------------------------------------------
// <auto-generated>
// 		This code was generated by a tool on 10/18/2015 22:21:04.
// 
//		Changes to this file may cause incorrect behavior and will be
// 			list if the code is re-generated.
// 
// Output files: AssemblyInfo.cs and the configured nuspec file
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("SchwabenCode.Data.Entity")]
[assembly: AssemblyDescription("Entity Handling by SchwabenCode")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Benjamin Abt (SchwabenCode.com)")]
[assembly: AssemblyProduct("SchwabenCode.Data.Entity")]
[assembly: AssemblyCopyright("Copyright Benjamin Abt (SchwabenCode.com) 2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("7d924bd4-bccd-4747-a699-f71b68d8ba35")]

[assembly: AssemblyVersion("0.0.2")]
[assembly: AssemblyFileVersion("0.0.0.2")]

